name: Feature ci workflow

on:
  push:
    branches:
      - feature/*

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  test:
    name: Unit testing
    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run linter
        run: npm run test

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run coverage
        run: npm run coverage

  merge_to_dev:
    name: Merge to dev branch
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout dev branch
        run: |
          git checkout dev || git checkout -b dev 

      - name: Merge to dev
        env:
          PAT_TOKEN: ${{ secrets.PAT_KEY }}
        run: |
          git merge --no-ff ${{ github.ref_name }} -m "Merge $FEATURE_BRANCH into dev"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git dev
